/**
 * Client-side copy of the rejection code descriptions.
 * Mirrors backend/app/services/rejection_codes.py
 */
export const REJECTION_CODE_DESCRIPTIONS = {
  'CDSX-ATON-NM-001': 'LEGAL NAME MISMATCH BETWEEN DELIVERING AND RECEIVING RECORDS',
  'FS-ATON-RA-002':   'REGISTERED ACCOUNT TYPE MISMATCH',
  'FS-ATON-IA-003':   'FRACTIONAL SHARES DETECTED — IN-KIND TRANSFER NOT PERMITTED',
  'FS-ATON-MF-004':   'PROPRIETARY MUTUAL FUND / ASSET TYPE NOT SUPPORTED',
}
